#ifndef SCASE1_PLUGIN_DOCUMENTWRITER_GLOBAL_H
#define SCASE1_PLUGIN_DOCUMENTWRITER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCASE1_PLUGIN_DOCUMENTWRITER_LIBRARY)
#  define SCASE1_PLUGIN_DOCUMENTWRITERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCASE1_PLUGIN_DOCUMENTWRITERSHARED_EXPORT Q_DECL_IMPORT
#endif

#define SCASE1_PLUGIN_DOCUMENTWRITER_NAME "net.adapar.SCASE1.plugins.DocumentWriter/1.0"
#define SCASE1_PLUGIN_DOCUMENTWRITER_BROWSER_TREE_FILE "DocumentWriter.browserTree"
#define SCASE1_PLUGIN_DOCUMENTWRITER_SETTINGS_FILE "DocumentWriter"

#endif // SCASE1_PLUGIN_DOCUMENTWRITER_GLOBAL_H
