/'

    SCASE: extendable prototype of an assistive communication tool for people with Locked-in Syndrome

    Copyright (C) 2014  Andrés Aparicio

    This file is part of SCASE.

    SCASE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    SCASE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SCASE.  If not, see <http://www.gnu.org/licenses/>.

    '/

@startuml "images/sequence_07_startup_dw_plugin.png"

!include common.ipu

== configuración == 
create plugin << DocumentWriterPlugin >>
[-> plugin : nuevo
create settings << QSettings >>
plugin -> settings : nuevo
plugin -> settings : leer configuración
create presentationWidget << DWPTextEdit >>
plugin -> presentationWidget : nuevo
plugin -> presentationWidget : configuración básica

... continúa la inicialización de los demás módulos ...

== configuración del elemento de presentación ==

[-> plugin : solicitud de configuración elemento de presentación
plugin -> plugin : calcular valores
plugin --> presentationWidget : asignar valores calculados

@enduml
