/'

    SCASE: extendable prototype of an assistive communication tool for people with Locked-in Syndrome

    Copyright (C) 2014  Andrés Aparicio

    This file is part of SCASE.

    SCASE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    SCASE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SCASE.  If not, see <http://www.gnu.org/licenses/>.

    '/

@startuml "images/sequence_06_invoke_plugin_action.png"

!include common.ipu

participant browser << Browser >>
participant pluginHandler << PluginHandler >>
participant plugin << IPlugin >>

browser -->o pluginHandler : enviar <b><i>executeActionFromPlugin</i></b>
pluginHandler -> pluginHandler : verificar que el módulo de extensión solicitado exista

alt si el módulo de extensión existe

	pluginHandler -> plugin : invocar acción
	note right : el proceso específico depende del módulo de extensión,\nal igual que el reinicio del ciclo de presentación

end

@enduml
	