/'

    SCASE: extendable prototype of an assistive communication tool for people with Locked-in Syndrome

    Copyright (C) 2014  Andrés Aparicio

    This file is part of SCASE.

    SCASE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    SCASE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SCASE.  If not, see <http://www.gnu.org/licenses/>.

    '/

@startuml "images/sequence_03_startup_pluginhandler.png"

!include common.ipu

participant pluginHandler << PluginHandler >>
participant mainWindow << MainWindow >>
participant browser << Browser >>

mainWindow -> pluginHandler : configurar módulos de extensión
mainWindow -> pluginHandler : obtener lista de módulos de extensión disponibles

loop por cada módulo de extensión encontrado
	create plugin << IPlugin >>
	pluginHandler -> plugin  : cargar
	alt módulo existe y es válido
		plugin --> pluginHandler : insertar en el directorio interno
		browser --> plugin : asignar delegado de navegación
		browser -> plugin  : obtener árbol de acciones
		create rootItem << BrowserItem >>
		browser -> rootItem : interpretar árbol de acciones
		rootItem --> plugin : asignar delegado de árbol de navegación
		plugin --> rootItem : asignar delegado de módulo de extensión
		rootItem --> browser : insertar en el nivel raíz
		create pluginWidget << QWidget >>
		plugin --> pluginWidget : obtener elemento de retroalimentación
		pluginWidget --> mainWindow : agregar
	end
end

@enduml
