/'

    SCASE: extendable prototype of an assistive communication tool for people with Locked-in Syndrome

    Copyright (C) 2014  Andrés Aparicio

    This file is part of SCASE.

    SCASE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    SCASE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SCASE.  If not, see <http://www.gnu.org/licenses/>.

    '/

@startuml "images/sequence_04_presentation_loop.png"

!include common.ipu

participant browser << Browser >>
participant timer << QTimer >>
participant currentLevel << BrowserLevel >>
participant currentItem << BrowserItem >>
participant presentationDelegate << BrowserPresentationWidget >>

timer -->o browser : enviar <b><i>timeout</i></b>
browser -> timer : detener
browser -> currentLevel : avanzar
currentLevel --> currentItem : obtener item actual

alt si no hay item actual
	alt si está en la raíz
		browser -> browser : volver al inicio del nivel raíz
	else no está en la raíz
		alt si el estado es lectura de ítems del árbol
			browser -> browser : cambiar estado a lectura de pseudo-ítems
		else el estado es lectura de pseudo-ítems
			browser -> browser : cambiar estado a lectura de ítems del árbol
			browser -> browser : volver al inicio del nivel raíz
		end
	end
end

alt si el estado es lectura de ítems del árbol
	currentItem --> presentationDelegate : actualizar información
else el estado es lectura de pseudo-ítems
	browser --> presentationDelegate : actualizar con información de pseudo-ítem
end

browser -> timer : empezar cuenta de tiempo

@enduml
